language: node_js
node_js:
  - "10"
  - "9"
install:
  - npm install
os:
  - linux

stages:
  - test
  - name: deploy

jobs:
  include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Testing Started ..."
        - npm test
        - echo "Testing Finished."

    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - git branch newbranch
        - git branch
        - git checkout newbranch
        - cd npm_package/
        - npm version patch
        - cd ../build_package/
        - npm version patch
        - cd ../
        - cp -f npm_package/package.json ./
        - npm run lib
        - echo "NPM Building Finished."

      deploy:
        provider: npm
        email: t@tsy6.com
        api_key: "$NPM_TOKEN"   # NPM_TOKEN 是在 Travis 中配置的 npm token 的名称
        skip_cleanup: true
        on:
          all_branches: true

      after_script:
        - cp -f build_package/package.json ./
        - ls
        - git config user.name "Travis"
        - git config user.email "t@tsy6.com"
        - git add .
        - git commit -m "Travis CI Auto Builder"
        - git status
        - git checkout master
        - git merge newbranch
        - git push "https://${GH_TOKEN}@${GH_REF}" master:master # GH_TOKEN 是在 Travis 中配置 github token 的名称
        - git branch -D newbranch
        - git branch

env:
  global:
    - GH_REF: github.com/TangSY/vue-hash-calendar.git #github仓库地址
