language : node_js
node_js:
 - "10"
 - "9"
install:
- npm install
os:
 - linux

stages:
 - test
 - name: deploy

jobs:
 include:
   - stage: test
     script:
       - node --version
       - npm --version
       - echo "Testing Started ..."
       - npm test
       - echo "Testing Finished."

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm run build
       - cd npm_package/
       - npm version patch
       - cd ../
       - cp -f npm_package/package.json ./
       - npm run lib
       - git add .
       - git commit -m "travis"
       - git push origin master
       - echo "NPM Building Finished."

     deploy:
       provider: npm
       email: t@tsy6.com
       api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true